#!/usr/bin/env bash
# This script displays To infinity ans beyond indefinitely
# with a sleep 2 in between each iteration

trap 'ech "I am invincible!!!"' SIGTERM
while :
do
	echo "To infinity and beyond"
	sleep 2
done
