#!/usr/bin/env bash
# This script displays numbers from 1 to 20 in addition to:
#    "bad luck from China" for the 4th iteration
#    "bad luck from Japan" for the 9th iteration
#    "bad luck from Italy" for the 17thiteration.

count=1

while [ $count -le 20 ]
do
   echo "$count"
   case $count in
      "4") echo "bad luck fron China";;
      "9") echo "bad luck fron Japan";;
      "17") echo "bad luck from Italy";;
   esac
   (( count++ ))
done
